#!/usr/bin/env bash
# debugging nginx port 80
# How It solved it
# ../sites-available/default
# NB: The flag -s creates a symbolic link, -f deletes the existing file
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
