#!/usr/bin/env bash
# debugging nginx port 80
# How to solved it
# ../sites-available/default
# NB: The -s flag creates a symbolic link and -f deletes the existing file
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
