#!/usr/bin/env bash
#This script displays To infinity and beyond indefinitely
#and h a sleep 2 in between each iteration

i=1
trap 'echo "I am invincible!!!"' SIGTERM
while [ $i ]; do
      echo "To infinity and beyond"
      sleep 2
done