#!/usr/bin/env bash
#This script displays numbers from 1 to 20
#displays 4 and then "bad luck from China" in the 4 loop iteration
#displays 9 and then "bad luck from Japan" in the 9 loop iteration
#displays 17 and "then bad luck from Italy" in the 17 loop iteration
i=1
while ((i <= 20))
do
    echo $i
    case $i in
        4)
            echo "bad luck from China";;
        9)
            echo "bad luck from Japan";;
        17)
            echo "bad luck from Italy";;
    esac
    ((i++))
done