#!/usr/bin/env bash
# Fixes a web server to run Nginx 

# set a user in the config by replace '#user'
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give owner permissions to read and write
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill the process 
pkill apache2
# start the nginx service with the new nginx user
sudo -u nginx service nginx start
